#!/usr/bin/env python3
"""
Query XDF v2.09b JSON Export for Spark Cut Relevant Entries
============================================================
Searches the Enhanced v2.09b XDF JSON export for all parameters related to
the spark cut / rev limiter implementation: dwell, EST, fuel cut, timing,
knock, RPM limits, and torque management.

Usage:
    python query_xdf_for_sparkcut.py

Requires:
    xdf_exports/Enhanced_v209b_export.json  (generated by tunerpro_xdf_parser.py)

Outputs:
    Console listing of matching scalars, tables, and flags with addresses,
    values, and descriptions. Used to cross-reference addresses in ASM patches.

Author:  Jason King (KingAI Tuning)
Date:    January 2026
Repo:    https://github.com/KingAiCodeForge/kingaustraliagg-vy-l36-060a-enhanced-asm-patches
Status:  ✅ WORKING — produces correct output, verified against v2.09b XDF

See also:
    - VY_V6_SPARK_CUT_IMPLEMENTATION_GUIDE.md (master spark cut doc)
    - custom_ose_$060_445_plan.md §3 (rev limit & spark cut plan)
    - TOOLS_MASTER_CATALOG.md (full script inventory)
"""
import json
import os

BASE = r'A:\VY_V6_Assembly_Modding'
XDF_JSON = os.path.join(BASE, 'xdf_exports', 'Enhanced_v209b_export.json')

with open(XDF_JSON, 'r', encoding='utf-8', errors='replace') as f:
    xdf = json.load(f)

# Keywords for spark cut project
keywords = [
    'fuel cut', 'rev lim', 'dwell', 'spark', 'rpm limit', 'fco',
    'fuel shut', 'est ', 'crank period', '3x period', 'burn time',
    'min dwell', 'max burn', 'ignition', 'coil', 'timing advance',
    'knock retard', 'fuel cutoff', 'high speed', 'rpm shut',
    'torque management', 'torque reduction', 'shift torque',
]

print('=' * 100)
print('XDF v2.09b ENTRIES RELEVANT TO SPARK CUT PATCH')
print('=' * 100)

for section in ['scalars', 'tables', 'flags']:
    matches = []
    for item in xdf.get(section, []):
        title = item.get('title', '')
        tl = title.lower()
        if any(kw in tl for kw in keywords):
            matches.append(item)
    
    if matches:
        print(f'\n--- {section.upper()} ({len(matches)} matches) ---')
        for item in matches:
            addr = item.get('address', None)
            title = item.get('title', '?')
            val = item.get('value', item.get('raw_value', ''))
            raw = item.get('raw_value', '')
            
            if addr is not None and isinstance(addr, int):
                # Determine bank from file offset
                bank = addr // 0x8000
                cpu = 0x8000 + (addr % 0x8000) if bank > 0 else addr
                addr_str = f'file=0x{addr:05X} bank={bank} cpu=${cpu:04X}'
            elif addr is not None:
                addr_str = f'addr={addr}'
            else:
                addr_str = 'NO ADDRESS'
            
            print(f'  {addr_str}  {title}')
            if val:
                print(f'    value={val}  raw={raw}')

# Now specifically look for the addresses we care about
print('\n' + '=' * 100)
print('SPECIFIC ADDRESS LOOKUPS')
print('=' * 100)

# Build address index
addr_index = {}
for section in ['scalars', 'tables', 'flags']:
    for item in xdf.get(section, []):
        addr = item.get('address', None)
        if addr is not None and isinstance(addr, int):
            if addr not in addr_index:
                addr_index[addr] = []
            addr_index[addr].append((section, item.get('title', '?'), item.get('value', '')))

# Key addresses from our ASM patches
key_addresses = {
    0x77DE: 'Fuel Cut RPM HIGH (Drive)',
    0x77DF: 'Fuel Cut RPM LOW (Drive)',
    0x77E0: 'Fuel Cut RPM HIGH (P/N)',
    0x77E1: 'Fuel Cut RPM LOW (P/N)',
    0x171AA: 'Min Dwell (from v37 dwell patch)',
    0x19813: 'Min Burn (from v37 dwell patch)',
}

# Also check direct RAM-like addresses (lower 16-bit space)
ram_addresses = {
    0x00A2: 'RPM/25',
    0x0046: 'Engine Mode Flags',
    0x017B: 'Dwell Intermediate',
    0x0199: 'Dwell Time RAM',
    0x194C: 'Crank Period 24X',
    0x0190: 'Timing Advance',
    0x013F: 'Injector PW Bank 1',
    0x0141: 'Injector PW Bank 2',
    0x01A0: 'WRONG? (0 refs)',
    0x0160: 'WRONG? (0 refs)',
    0x00EF: 'WRONG? RPM_ZONE_75',
}

print('\n--- Calibration addresses ---')
for addr, name in sorted(key_addresses.items()):
    if addr in addr_index:
        for sec, title, val in addr_index[addr]:
            print(f'  0x{addr:05X}: [{sec}] "{title}" = {val}')
    else:
        # Check near addresses
        found = False
        for offset in range(-2, 3):
            check = addr + offset
            if check in addr_index and check != addr:
                for sec, title, val in addr_index[check]:
                    print(f'  0x{addr:05X}: NOT FOUND, but 0x{check:05X} has [{sec}] "{title}"')
                    found = True
        if not found:
            print(f'  0x{addr:05X}: NOT IN XDF ({name})')

print('\n--- RAM addresses (should NOT be in XDF as they are runtime-only) ---')
for addr, name in sorted(ram_addresses.items()):
    if addr in addr_index:
        for sec, title, val in addr_index[addr]:
            print(f'  ${addr:04X}: [{sec}] "{title}" = {val}  <-- UNEXPECTED!')
    else:
        print(f'  ${addr:04X}: Not in XDF (correct - {name} is runtime RAM)')

# Find all XDF entries in the patch free space range
print('\n--- XDF entries in Bank 1 free space ($C468-$FFBF / file 0x0C468-0x0FFBF) ---')
free_start = 0x0C468
free_end = 0x0FFBF
count = 0
for addr in sorted(addr_index.keys()):
    if free_start <= addr <= free_end:
        for sec, title, val in addr_index[addr]:
            print(f'  0x{addr:05X}: [{sec}] "{title}"')
            count += 1
if count == 0:
    print('  NONE - Free space is clean (good!)')

# Find fuel cut related tables with full data
print('\n--- FUEL CUT TABLE DETAILS ---')
for item in xdf.get('tables', []) + xdf.get('scalars', []):
    title = item.get('title', '').lower()
    if 'fuel cut' in title or 'fuel shut' in title or ('fco' in title and 'rpm' in title):
        print(f'\n  Title: {item.get("title", "?")}')
        addr = item.get('address', '?')
        if isinstance(addr, int):
            bank = addr // 0x8000
            cpu = 0x8000 + (addr % 0x8000) if bank > 0 else addr
            print(f'  Address: file=0x{addr:05X}, bank={bank}, cpu=${cpu:04X}')
        print(f'  Value: {item.get("value", "?")}')
        print(f'  Raw: {item.get("raw_value", "?")}')
        # Show data if table
        if 'data' in item:
            print(f'  Data: {item["data"][:200]}...' if len(str(item["data"])) > 200 else f'  Data: {item["data"]}')

# Show dwell-related entries
print('\n--- DWELL/BURN CONSTANTS ---')
for item in xdf.get('scalars', []):
    title = item.get('title', '').lower()
    if 'dwell' in title or 'burn' in title:
        addr = item.get('address', '?')
        val = item.get('value', '?')
        raw = item.get('raw_value', '?')
        if isinstance(addr, int):
            bank = addr // 0x8000
            cpu = 0x8000 + (addr % 0x8000) if bank > 0 else addr
            print(f'  0x{addr:05X} (bank {bank} ${cpu:04X}): "{item["title"]}" = {val} (raw={raw})')
        else:
            print(f'  {addr}: "{item["title"]}" = {val}')

# Summary stats
print('\n--- XDF v2.09b SUMMARY ---')
print(f'  Total scalars: {len(xdf.get("scalars", []))}')
print(f'  Total tables:  {len(xdf.get("tables", []))}')
print(f'  Total flags:   {len(xdf.get("flags", []))}')
print(f'  Total patches: {len(xdf.get("patches", []))}')
print(f'  Unique addresses indexed: {len(addr_index)}')
print(f'  Definition name: {xdf.get("definition_name", "?")}')
