#!/usr/bin/env python3
"""
VY V6 128KB Binary Splitter, Disassembler & Differ
===================================================
Splits 128KB Delco HC11 bins into 3 flash banks per OSE Flash Tool mapping,
disassembles each bank with Capstone M680X (HC11 mode), and diffs STOCK vs Enhanced.

Bank layout from OSE Flash Tool decompilation (ALDLFunctions.cs):
  Bank 1: bin[0x00000:0x10000] → 64 KB → CPU 0x0000-0xFFFF (primary window)
  Bank 2: bin[0x10000:0x18000] → 32 KB → CPU 0x8000-0xFFFF (paged via PORTC bit 3)
  Bank 3: bin[0x18000:0x20000] → 32 KB → CPU 0x8000-0xFFFF (paged)

Usage:
  python split_and_disassemble.py                    # Split & disassemble all
  python split_and_disassemble.py --diff             # Also diff STOCK vs Enhanced
  python split_and_disassemble.py --split-only       # Just split, no disassembly
"""

import os
import sys
import struct
import argparse
from pathlib import Path

# --- Configuration ---
BINS = {
    "STOCK": "92118883_STOCK.bin",
    "Enhanced_v1.0a": "VX-VY_V6_$060A_Enhanced_v1.0a - Copy.bin",
    "Enhanced_v1.1a": "VX-VY_V6_$060A_Enhanced_v1.1a.bin",
    "Enhanced": "VY_V6_Enhanced.bin",
}

# Bank definitions: (name, bin_start, bin_end, cpu_base_address)
BANKS = [
    ("bank1", 0x00000, 0x10000, 0x0000),  # 64KB, CPU $0000-$FFFF
    ("bank2", 0x10000, 0x18000, 0x8000),  # 32KB, CPU $8000-$FFFF (paged)
    ("bank3", 0x18000, 0x20000, 0x8000),  # 32KB, CPU $8000-$FFFF (paged)
]

# HC11 vector table at $FFF0-$FFFF (in bank 1 only)
VECTORS = {
    0xFFD6: "SCI",
    0xFFD8: "SPI",
    0xFFDA: "PAI_Edge",
    0xFFDC: "PA_Overflow",
    0xFFDE: "Timer_Overflow",
    0xFFE0: "OC5",
    0xFFE2: "OC4",
    0xFFE4: "OC3",
    0xFFE6: "OC2",
    0xFFE8: "OC1",
    0xFFEA: "IC3",
    0xFFEC: "IC2",
    0xFFEE: "IC1",
    0xFFF0: "RTI",
    0xFFF2: "IRQ",
    0xFFF4: "XIRQ",
    0xFFF6: "SWI",
    0xFFF8: "Illegal_Opcode",
    0xFFFA: "COP_Watchdog",
    0xFFFC: "Clock_Monitor",
    0xFFFE: "RESET",
}

# Known address labels from XDF/disassembly work
KNOWN_LABELS = {
    # EEPROM/NVRAM
    0x0E00: "EEPROM_VIN",
    0x0F00: "EEPROM_End",
    # Calibration region
    0x2000: "CalStart",
    0x4000: "FlashCalStart",
    0x4006: "Checksum_HI",
    0x4007: "Checksum_LO",
    0x5FFF: "CalEnd",
    # Program region
    0x7FF0: "CalID",
    0x8000: "ProgROM_Start",
    0xFF80: "ProgID",
    # I/O registers
    0x1000: "PORTA",
    0x1003: "PORTC",  # Bank switching bit 3 = A16
    0x1004: "PORTB",
    0x1008: "PORTD",
    0x1009: "DDRD",
    0x100E: "TCNT_H",
    0x100F: "TCNT_L",
    0x1020: "ADCTL",
    0x1028: "SPCR",
    0x102B: "BAUD",
    0x102C: "SCCR1",
    0x102D: "SCCR2",
    0x102E: "SCSR",
    0x102F: "SCDR",
    0x103C: "INIT",
    0x103D: "TEST1",
}

OUTPUT_DIR = Path("bank_split_output")


def read_bin(filepath):
    """Read a binary file and validate it's 128KB."""
    with open(filepath, "rb") as f:
        data = f.read()
    if len(data) != 131072:
        print(f"  WARNING: {filepath} is {len(data)} bytes, expected 131072 (128KB)")
    return data


def split_bin(data, name, output_dir):
    """Split a 128KB binary into 3 bank files."""
    bank_files = []
    for bank_name, start, end, cpu_base in BANKS:
        bank_data = data[start:end]
        out_path = output_dir / f"{name}_{bank_name}.bin"
        with open(out_path, "wb") as f:
            f.write(bank_data)
        bank_files.append((bank_name, out_path, bank_data, cpu_base))
        print(f"  {bank_name}: {out_path.name} ({len(bank_data)} bytes, CPU ${cpu_base:04X}-${cpu_base + len(bank_data) - 1:04X})")
    return bank_files


def extract_vectors(bank1_data):
    """Extract interrupt vector table from bank 1 data."""
    lines = []
    lines.append("\n; === HC11 Interrupt Vector Table ($FFD6-$FFFF) ===")
    for addr in sorted(VECTORS.keys()):
        offset = addr  # bank1 is loaded at CPU $0000, so offset = addr
        if offset + 1 < len(bank1_data):
            vec_hi = bank1_data[offset]
            vec_lo = bank1_data[offset + 1]
            vec_target = (vec_hi << 8) | vec_lo
            label = VECTORS[addr]
            lines.append(f"; ${addr:04X}: {label:20s} -> ${vec_target:04X}")
    return "\n".join(lines)


def disassemble_bank(bank_data, cpu_base, bank_name, name, output_dir):
    """Disassemble a bank using Capstone HC11."""
    from capstone import Cs, CS_ARCH_M680X, CS_MODE_M680X_6811

    md = Cs(CS_ARCH_M680X, CS_MODE_M680X_6811)
    md.detail = False  # Faster without detail

    out_path = output_dir / f"{name}_{bank_name}.asm"
    bank_size = len(bank_data)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"; {name} {bank_name} Disassembly\n")
        f.write(f"; Generated by split_and_disassemble.py\n")
        f.write(f"; CPU Base: ${cpu_base:04X}  Size: {bank_size} bytes ({bank_size // 1024}KB)\n")
        f.write(f"; Bin offset: ${BANKS[['bank1','bank2','bank3'].index(bank_name)][1]:05X}\n")
        f.write(f";\n")

        # Add vector table for bank 1
        if bank_name == "bank1":
            f.write(extract_vectors(bank_data))
            f.write("\n;\n")

        f.write(f"\n        .org    ${cpu_base:04X}\n\n")

        # Track position for data gaps
        pos = 0
        last_addr = cpu_base
        insn_count = 0
        data_bytes = 0

        # Regions to treat as data (calibration tables in bank 1)
        data_regions = []
        if bank_name == "bank1":
            # $0000-$1FFF: I/O, RAM, EEPROM — mostly data
            data_regions.append((0x0000, 0x2000))
            # $2000-$3FFF: Calibration data (tables, not code)
            data_regions.append((0x2000, 0x4000))
            # $4000-$5FFF: More calibration
            data_regions.append((0x4000, 0x6000))

        for region_start, region_end in data_regions:
            rel_start = region_start - cpu_base
            rel_end = region_end - cpu_base
            if rel_start >= 0 and rel_end <= bank_size:
                # Write header
                label = KNOWN_LABELS.get(region_start, "")
                if label:
                    f.write(f"\n; === {label} (${region_start:04X}) ===\n")
                f.write(f"\n; --- Data region ${region_start:04X}-${region_end - 1:04X} ({region_end - region_start} bytes) ---\n")

                # Write as .byte directives, 16 per line
                for i in range(rel_start, rel_end, 16):
                    addr = cpu_base + i
                    chunk = bank_data[i:min(i + 16, rel_end)]
                    hex_str = ", ".join(f"${b:02X}" for b in chunk)
                    ascii_str = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
                    label_str = ""
                    if addr in KNOWN_LABELS:
                        label_str = f"  ; << {KNOWN_LABELS[addr]}"
                    f.write(f"L{addr:04X}:  .byte   {hex_str:48s} ; |{ascii_str}|{label_str}\n")
                    data_bytes += len(chunk)

        # Disassemble code regions
        code_start = 0
        if bank_name == "bank1":
            code_start = 0x6000  # Skip data regions, start code at $6000

        code_data = bank_data[code_start:]
        code_base = cpu_base + code_start

        f.write(f"\n; === Code region ${code_base:04X}-${cpu_base + bank_size - 1:04X} ===\n\n")

        for insn in md.disasm(code_data, code_base):
            # Add known labels
            if insn.address in KNOWN_LABELS:
                f.write(f"\n; --- {KNOWN_LABELS[insn.address]} ---\n")

            # Add vector labels
            if insn.address in VECTORS:
                f.write(f"\n; --- Vector: {VECTORS[insn.address]} ---\n")

            # Format: address, hex bytes, mnemonic, operands
            raw_bytes = " ".join(f"{b:02X}" for b in insn.bytes)
            f.write(f"L{insn.address:04X}:  {raw_bytes:15s}  {insn.mnemonic:8s} {insn.op_str}\n")
            insn_count += 1

        # Summary
        f.write(f"\n; === Summary ===\n")
        f.write(f"; Instructions disassembled: {insn_count}\n")
        f.write(f"; Data bytes emitted: {data_bytes}\n")
        f.write(f"; Bank size: {bank_size} bytes\n")

    print(f"    → {out_path.name}: {insn_count} instructions, {data_bytes} data bytes")
    return out_path


def diff_banks(stock_data, enhanced_data, bank_name, cpu_base, output_dir, stock_name, enh_name):
    """Diff two bank binaries and report changes."""
    if len(stock_data) != len(enhanced_data):
        print(f"  WARNING: Size mismatch in {bank_name}: {len(stock_data)} vs {len(enhanced_data)}")
        return

    diffs = []
    run_start = None
    run_stock = bytearray()
    run_enh = bytearray()

    for i in range(len(stock_data)):
        if stock_data[i] != enhanced_data[i]:
            if run_start is None:
                run_start = i
                run_stock = bytearray()
                run_enh = bytearray()
            run_stock.append(stock_data[i])
            run_enh.append(enhanced_data[i])
        else:
            if run_start is not None:
                diffs.append((run_start, bytes(run_stock), bytes(run_enh)))
                run_start = None

    if run_start is not None:
        diffs.append((run_start, bytes(run_stock), bytes(run_enh)))

    out_path = output_dir / f"diff_{stock_name}_vs_{enh_name}_{bank_name}.txt"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"Binary Diff: {stock_name} vs {enh_name} — {bank_name}\n")
        f.write(f"{'=' * 70}\n")
        f.write(f"Bank CPU base: ${cpu_base:04X}\n")
        f.write(f"Total differences: {len(diffs)} regions, {sum(len(s) for _, s, _ in diffs)} bytes changed\n\n")

        # Classify changes by region
        cal_changes = 0
        code_changes = 0
        eeprom_changes = 0

        for offset, stock_bytes, enh_bytes in diffs:
            addr = cpu_base + offset
            region = "CODE"
            if bank_name == "bank1":
                if 0x0E00 <= addr <= 0x0FFF:
                    region = "EEPROM"
                    eeprom_changes += len(stock_bytes)
                elif 0x2000 <= addr <= 0x5FFF:
                    region = "CAL"
                    cal_changes += len(stock_bytes)
                elif addr < 0x2000:
                    region = "LOW"
                else:
                    code_changes += len(stock_bytes)
            else:
                code_changes += len(stock_bytes)

            label = KNOWN_LABELS.get(addr, "")
            label_str = f"  ({label})" if label else ""

            f.write(f"[{region}] ${addr:04X}-${addr + len(stock_bytes) - 1:04X} ({len(stock_bytes)} bytes){label_str}\n")

            # Show bytes (up to 32 per diff region)
            show_count = min(len(stock_bytes), 32)
            stock_hex = " ".join(f"{b:02X}" for b in stock_bytes[:show_count])
            enh_hex = " ".join(f"{b:02X}" for b in enh_bytes[:show_count])
            if len(stock_bytes) > 32:
                stock_hex += f" ... (+{len(stock_bytes) - 32} more)"
                enh_hex += f" ... (+{len(enh_bytes) - 32} more)"
            f.write(f"  STOCK:    {stock_hex}\n")
            f.write(f"  ENHANCED: {enh_hex}\n\n")

        f.write(f"\n{'=' * 70}\n")
        f.write(f"Summary for {bank_name}:\n")
        if bank_name == "bank1":
            f.write(f"  CAL region changes:    {cal_changes} bytes\n")
            f.write(f"  EEPROM changes:        {eeprom_changes} bytes\n")
            f.write(f"  Code region changes:   {code_changes} bytes\n")
        else:
            f.write(f"  Code/table changes:    {code_changes} bytes\n")
        f.write(f"  Total changed regions: {len(diffs)}\n")
        f.write(f"  Total changed bytes:   {sum(len(s) for _, s, _ in diffs)}\n")

    print(f"    → {out_path.name}: {len(diffs)} regions, {sum(len(s) for _, s, _ in diffs)} bytes changed")
    if bank_name == "bank1":
        print(f"       CAL: {cal_changes}B, EEPROM: {eeprom_changes}B, CODE: {code_changes}B")
    return out_path


def main():
    parser = argparse.ArgumentParser(description="VY V6 128KB Binary Splitter & Disassembler")
    parser.add_argument("--split-only", action="store_true", help="Only split, skip disassembly")
    parser.add_argument("--diff", action="store_true", help="Diff STOCK vs all Enhanced variants")
    parser.add_argument("--bins", nargs="+", choices=list(BINS.keys()), default=None,
                        help="Which bins to process (default: all)")
    args = parser.parse_args()

    base_dir = Path(__file__).parent
    os.chdir(base_dir)

    OUTPUT_DIR.mkdir(exist_ok=True)

    # Filter bins
    bins_to_process = args.bins or list(BINS.keys())

    # Phase 1: Split
    print("=" * 60)
    print("PHASE 1: Split 128KB binaries into banks")
    print("=" * 60)

    all_banks = {}  # name → [(bank_name, path, data, cpu_base), ...]

    for name in bins_to_process:
        filename = BINS[name]
        filepath = base_dir / filename
        if not filepath.exists():
            print(f"\n  SKIP {name}: {filename} not found")
            continue

        print(f"\n  {name}: {filename}")
        data = read_bin(filepath)
        bank_files = split_bin(data, name, OUTPUT_DIR)
        all_banks[name] = bank_files

    # Phase 2: Disassemble
    if not args.split_only:
        print(f"\n{'=' * 60}")
        print("PHASE 2: Disassemble each bank (Capstone HC11)")
        print("=" * 60)

        for name, bank_files in all_banks.items():
            print(f"\n  {name}:")
            for bank_name, path, bank_data, cpu_base in bank_files:
                disassemble_bank(bank_data, cpu_base, bank_name, name, OUTPUT_DIR)

    # Phase 3: Diff
    if args.diff and "STOCK" in all_banks:
        print(f"\n{'=' * 60}")
        print("PHASE 3: Diff STOCK vs Enhanced")
        print("=" * 60)

        stock_banks = {b[0]: b for b in all_banks["STOCK"]}

        for name in bins_to_process:
            if name == "STOCK":
                continue
            if name not in all_banks:
                continue

            print(f"\n  STOCK vs {name}:")
            enh_banks = {b[0]: b for b in all_banks[name]}

            for bank_name in ["bank1", "bank2", "bank3"]:
                if bank_name in stock_banks and bank_name in enh_banks:
                    _, _, stock_data, cpu_base = stock_banks[bank_name]
                    _, _, enh_data, _ = enh_banks[bank_name]
                    diff_banks(stock_data, enh_data, bank_name, cpu_base,
                               OUTPUT_DIR, "STOCK", name)

    # Summary
    print(f"\n{'=' * 60}")
    print(f"Output directory: {OUTPUT_DIR.resolve()}")
    out_files = sorted(OUTPUT_DIR.iterdir())
    print(f"Files generated: {len(out_files)}")
    for f in out_files:
        size_kb = f.stat().st_size / 1024
        print(f"  {f.name} ({size_kb:.1f} KB)")
    print("=" * 60)


if __name__ == "__main__":
    main()
